version: '3'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: colter-harris-site-dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
