version: '3'

services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: colter-harris-site-prod
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - .:/app
